MCU = RP2040
BOOTLOADER = rp2040
BOARD = GENERIC_RP_RP2040

# Basic features
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
BACKLIGHT_ENABLE = no
BOOTMAGIC_ENABLE = yes
VIA_ENABLE = yes
SPLIT_KEYBOARD = no
LTO_ENABLE = yes
EXTRAKEY_ENABLE = yes
NKRO_ENABLE = no
MATRIX_HAS_GHOST = yes
LOCKING_SUPPORT_ENABLE = yes
LOCKING_RESYNC_ENABLE = yes
